### ISSUE TITLE
Support DMs for puppeted users

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-discord#184]
- [ ] Support messages discord > matrix #183
- [ ] Support messages matrix < discord #183
- [ ] Support starting a conversation discord > matrix #183 
- [ ] Support starting a converastion matrix > discord #183

**Comment by immanuelfodor** [comment]
Oh snap, I just came from the project readme, it would be so great to have DMs supported, the only thing that keeps me the Discord app installed on my phone.

**Comment by immanuelfodor** [comment]
Nevermind, I've just found https://github.com/matrix-discord/mx-puppet-discord with some more google-fu applied and it seems to support DMs
